name: bank_app
description: A flutter bank applicaition
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  gap:
  fl_chart:
  flutter_lints: ^2.0.0
  shared_preferences: ^2.0.12
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans_Regular.ttf
        - asset: assets/fonts/DMSans_Medium.ttf
        - asset: assets/fonts/DMSans_Bold.ttf

    - family: IconlyBold
      fonts:
        - asset: assets/fonts/Iconly_Bold.ttf

    - family: IconlyBroken
      fonts:
        - asset: assets/fonts/Iconly_Light.ttf

  assets:
    - assets/
    - assets/memoji/
    - assets/cards/